my-app/config/routes.rb
Rails.application.routes.draw do
  root to: 'lectures#index'
  get 'lecturers', to: 'lecturers#index'
  get 'lecture_names', to: 'lecture_names#index'
  
  resources :lectures
  resources :lecturers,only: [:index,:show,:new,:create]
  resources :lecture_names,only: [:index,:show,:new,:create]
  resources :kinds,only: [:index,:show,:new,:create]
  
  
end

my-app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

my-app/app/models/kind.rb
class Kind < ApplicationRecord
  validates :content, presence: true, length: { maximum: 50 }
  
  has_many :lecture
end

my-app/app/models/lecture.rb
class Lecture < ApplicationRecord
  belongs_to :lecture_name
  belongs_to :lecturer
  belongs_to :kind
  
  validates :content, presence: true, length: { maximum: 255 }
  validates :year, presence: true
  
  mount_uploader :image, ImagesUploader
end

my-app/app/models/lecture_name.rb
class LectureName < ApplicationRecord
  validates :content, presence: true, length: { maximum: 50 }
  
  has_many :lecture
end

my-app/app/models/lecturer.rb
class Lecturer < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  
  has_many :lecture
end

my-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

my-app/app/controllers/kinds_controller.rb
class KindsController < ApplicationController
  def index
    @kinds = Kind.all 
  end
  
  def show
    @kind = Kind.find(params[:id])
    @lectures = @kind.lecture.order('created_at DESC').page(params[:page])
  end
  
  def new
  end
  
  def create
  end
end

my-app/app/controllers/lecture_names_controller.rb
class LectureNamesController < ApplicationController
  def index
    @lecture_names = LectureName.all.page(params[:page])
  end
  
  def show
    @lecture_name = LectureName.find(params[:id])
    @lectures = @lecture_name.lecture.order('created_at DESC').page(params[:page])
  end
  
  def new
    @lecture_name = LectureName.new
  end
  
  def create
    @lecture_name = LectureName.new(lecture_name_params)

    if @lecture_name.save
      flash[:success] = '授業を登録しました。'
      redirect_to lecture_names_path
    else
      flash.now[:danger] = '授業の登録に失敗しました。'
      render :new
    end
  end
  
  private

  def lecture_name_params
    params.require(:lecture_name).permit(:content)
  end
end

my-app/app/controllers/lecturers_controller.rb
class LecturersController < ApplicationController
  def index
    @lecturers = Lecturer.all.page(params[:page])  
  end 
  
  def show
    @lecturer = Lecturer.find(params[:id])
    @lectures = @lecturer.lecture.order('created_at DESC').page(params[:page])
  end 
  
  def new
    @lecturer = Lecturer.new
  end
  
  def create
    @lecturer = Lecturer.new(lecturer_params)

    if @lecturer.save
      flash[:success] = '講師を登録しました。'
      redirect_to lecturers_path
    else
      flash.now[:danger] = '講師の登録に失敗しました。'
      render :new
    end
  end
  
  private

  def lecturer_params
    params.require(:lecturer).permit(:name)
  end
end

my-app/app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  def index
    @lectures = Lecture.all.page(params[:page])
  end

  def show
    @lecture = Lecture.find(params[:id])
  end

  def new
    @lecture = Lecture.new
    @lecturers = Lecturer.all
    @lecture_names = LectureName.all
    @kinds = Kind.all
  end
  
  def create
    @lecture = Lecture.new(lecture_params)

    if @lecture.save
      flash[:success] = '投稿が完了しました'
      redirect_to @lecture
    else
      flash.now[:danger] = '投稿できませんでした'
      render :new
    end
  end

  def edit
    @lecture = Lecture.find(params[:id])
    @lecturers = Lecturer.all
    @lecture_names = LectureName.all
    @kinds = Kind.all
  end
  
  def update
    @lecture = Lecture.find(params[:id])

    if @lecture.update(lecture_params)
      flash[:success] = '編集が完了しました'
      redirect_to @lecture
    else
      flash.now[:danger] = '編集できませんでした'
      render :edit
    end
  end 
  
  def destroy
    @lecture = Lecture.find(params[:id])
    @lecture.destroy
    
    flash[:success] = '投稿を削除しました。'
    redirect_back(fallback_location: root_path)
  end
  
  private

  def lecture_params
    params.require(:lecture).permit(:lecture_name_id,:lecturer_id,:year,:kind_id,:content,:image)
  end
end

my-app/app/helpers/application_helper.rb
module ApplicationHelper
end

my-app/app/helpers/kinds_helper.rb
module KindsHelper
end

my-app/app/helpers/lecture_names_helper.rb
module LectureNamesHelper
end

my-app/app/helpers/lectures_helper.rb
module LecturesHelper
end

my-app/app/views/lecture_names/index.html.erb
<h1>授業一覧</h1>

<% if @lecture_names.any? %>
  <ul class="media-list">
    <% @lecture_names.each do |lecture| %>
      <li class="media">
        <div class="media-body">
          <ul>
            <li><%= link_to lecture.content, lecture_name_path(lecture)%></li>
          </ul>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate @lecture_names %>
<% end %>

<p><%= link_to '授業登録ページへ', new_lecture_name_path, class: 'btn btn-primary' %></p>

my-app/app/views/lecture_names/new.html.erb
<div class="text-center">
  <h1>授業の登録</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@lecture_name) do |l| %>

      <div class="form-group">
        <%= l.label :content, 'Name' %>
        <%= l.text_field :content, class: 'form-control' %>
      </div>

      <%= l.submit '登録', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

<p><%= link_to '授業一覧ページへ', lecture_names_path, class: 'btn btn-primary' %></p>

my-app/app/views/lecture_names/show.html.erb
<h1><%= @lecture_name.content %>の 情報一覧</h1>

<% if @lectures.any? %>
<table class="table">
  <tr>
    <th class="text-center">ID</th>
    <th class="text-center">講師</th>
    <th class="text-center">年度</th>
    <th class="text-center">カテゴリー</th>
  </tr>
  <% @lectures.each do |lecture| %>
    <tr>
      <td><%= link_to lecture.id, lecture_path(lecture)%></td>
      <td class="text-center"><%= lecture.lecturer.name %></td>
      <td class="text-center"><%= lecture.year %></td>
      <td class="text-center"><%= lecture.kind.content %></td>
    </tr>
  <% end %>
  <%= paginate @lectures %>
<% else %>
  <p>情報はありません</p>
<% end %>